Section "ServerLayout"
    Identifier "SunshineLayout"
    Screen 0 "Screen0" 0 0
EndSection

Section "Monitor"
    Identifier "Monitor0"
    Option "Enable" "true"
EndSection

Section "Device"
    Identifier "Card0"
    Driver "nvidia"
    VendorName "NVIDIA Corporation"
    BusID "{{XORG_BUS_ID}}"
    Option "ConnectedMonitor" "{{XORG_OUTPUT_NAME}}"
    Option "CustomEDID" "{{XORG_OUTPUT_NAME}}:/etc/X11/edid/monitor-1080p.bin"
    Option "UseDisplayDevice" "{{XORG_OUTPUT_NAME}}"
    Option "MetaModes" "1920x1080"
    Option "AllowEmptyInitialConfiguration" "True"
    Option "ModeValidation" "NoDFPNativeResolutionCheck,NoVirtualSizeCheck,NoMaxPClkCheck,NoHorizSyncCheck,NoVertRefreshCheck,NoWidthAlignmentCheck,AllowNonEdidModes,NoMaxSizeCheck"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device "Card0"
    Monitor "Monitor0"
    DefaultDepth 24
    Option "TwinView" "True"
    SubSection "Display"
        Depth 24
        Modes "1920x1080"
        Virtual 1920 1080
    EndSubSection
EndSection
